services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./mysite:/usr/share/nginx/html
      - ./mysite:/mysite
    #   #- ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - learn-nginx
networks:
  learn-nginx:
    driver: bridge